export const USER_LOGGED = 'USER_LOGGED';
export const USER_REGISTER = 'USER_REGISTER';
export const FILTER_SHOW_RECIPES = 'FILTER_SHOW_RECIPES';
export const ADD_RECIPE = 'ADD_RECIPE';
export const DELETE_RECIPE = 'DELETE_RECIPE';
export const FAVORITE_RECIPE = 'FAVORITE_RECIPE';